# 应用配置
app:
  name: "NextEraAbyss/FiberForge"
  mode: "dev"
  port: 3000

# 数据库配置
mysql:
  host: "10.0.0.5"
  port: 3306
  username: "root"
  password: "xh87bxaT15sLQgR"
  database: "FiberForge"

# redis配置
redis:
  enable: false
  host: "10.0.0.5"
  port: "6379"
  database: 0
  password: "lLQpoNUu7QnfWsZ"

# 日志配置
log:
  level: "debug"
  filename: "./logs/app.log"
  max_size: 100    # MB
  max_backups: 30
  max_age: 7       # 天
  compress: true

# JWT配置
jwt:
  secret: "your-secret-key"
  expire: 86400  # 24小时

md5:
  hash: "asdsad!#$FREWE12314"

# true是dev环境,false是生产环境
debug: true

# rabbitmq配置
rabbitmq:
  enable: true
  username: "jOTBmYEprf28Seki"
  password: "Ogga7FS)MM$44EmM"
  host: "10.0.0.5"
  port: "5672"

# 邮件配置
email:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "Your App <your-email@gmail.com>"