# 应用配置
app:
  name: "NextEraAbyss/FiberForge"
  mode: "prod"
  port: 3000

# 数据库配置
mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "your-prod-password"
  database: "fiber_layout"

# redis配置
redis:
  enable: true
  host: "localhost"
  port: 6379
  database: 0
  password: "your-redis-password"

# 日志配置
log:
  level: "info"
  filename: "./logs/app.log"
  max_size: 100    # MB
  max_backups: 30
  max_age: 30      # 天
  compress: true

# JWT配置
jwt:
  secret: "your-production-secret-key"
  expire: 86400  # 24小时

md5:
  hash: "your-production-hash-key"

# true是dev环境,false是生产环境
debug: false

# rabbitmq配置
rabbitmq:
  enable: true
  username: "prod-user"
  password: "prod-password"
  host: "localhost"
  port: 5672

# 邮件配置
email:
  host: "smtp.gmail.com"
  port: 587
  username: "your-production-email@gmail.com"
  password: "your-production-app-password"
  from: "Your Production App <your-production-email@gmail.com>"